import {createRealmContext} from '@realm/react';
import {
  UserData,
  User,
  Region,
  Grade,
  SingleSubject,
  Subject,
  ExamQuestion,
  ExamAnswers,
  Exam,
  UserExamAnswers,
  Study,
  Pdf,
  VideoLink,
  StudyTips,
  SingleChallenge,
  ChallangeDay,
  Challange,
} from './index';
export const AuthContext = createRealmContext({
  schema: [
    UserData,
    User,
    Grade,
    Region,
    SingleSubject,
    Subject,
    ExamQuestion,
    ExamAnswers,
    Exam,
    UserExamAnswers,
    Study,
    Pdf,
    VideoLink,
    StudyTips,
    SingleChallenge,
    ChallangeDay,
    Challange,
  ],
  deleteRealmIfMigrationNeeded: true,
});
